/**
 * Every user-facing string in Horizon Task.
 *
 * Views never inline literals; they read from here. That keeps a future i18n
 * pass to a single file, and makes it obvious which copy still needs review.
 */

import type {
	DraftIssueCode,
	FrameworkLayer,
	FrameworkTerm,
	HierarchyIssueCode,
	Level,
	LevelChangeNoteCode,
	Priority,
	RolloverBehavior,
	SortMode,
	StatusCategory,
} from "./domain";

export const strings = {
	plugin: {
		name: "Horizon Task",
		ribbonTooltip: "Open the Horizon Task board",
	},

	/**
	 * Command names. Obsidian prefixes these with the plugin name itself, so the
	 * name must not repeat it and the id must not contain it either.
	 */
	commands: {
		openBoard: "Open board",
		openUserGuide: "Open user guide",
		newTask: "New task",
		editTask: "Edit task",
		undoLastChange: "Undo last task change",
	},

	/** The period format and an example, per horizon. Also used by the guide. */
	periodFormats: {
		daily: { format: "yyyy-MM-dd", example: "2026-09-28" },
		weekly: { format: "yyyy-'W'ww", example: "2026-W40" },
		monthly: { format: "yyyy-MM", example: "2026-09" },
		quarterly: { format: "yyyy-'Q'q", example: "2026-Q4" },
		yearly: { format: "yyyy", example: "2026" },
		objective: { format: "none", example: "—" },
	} satisfies Record<Level, { format: string; example: string }>,

	/** The task form, the parent picker and the card-level actions. */
	task: {
		createTitle: "New task",
		editTitle: "Edit task",
		title: { name: "Title" },
		titlePlaceholder: "What needs doing?",
		status: { name: "Status" },
		priority: { name: "Priority" },
		level: { name: "Horizon" },
		period: { name: "Period" },
		periodFormat: "Format {format}, for example {example}.",
		parent: {
			name: "Parent",
			desc: "Optional. Only tasks on an allowed horizon are offered.",
			choose: "Choose",
			clear: "Clear",
			none: "No parent",
		},
		parentPlaceholder: "Search for a parent task",
		parentEmpty: "No task on an allowed horizon matches",
		tags: {
			name: "Tags",
			desc: "Comma separated. Inline #tags in the note are read as well.",
			placeholder: "work, website",
		},
		due: { name: "Due", desc: "Optional, as yyyy-MM-dd." },
		body: {
			name: "Body",
			desc: "Starting text for the new note. Only the title is required.",
			editDesc:
				"Saving replaces the note's text. The frontmatter above is written separately, so nothing else changes.",
			placeholder: "Write the note…",
		},
		save: "Save",
		create: "Create",
		cancel: "Cancel",
		openNote: "Open note",
		delete: "Delete",

		/**
		 * The goal/execution framework an objective carries.
		 *
		 * Two layers of six terms: the first half designs the goal, the second half
		 * runs and reviews it. Each description is the meaning of the term, so the
		 * form explains itself without a separate help page.
		 */
		framework: {
			heading: "Goal and execution framework",
			intro:
				"Objectives are the only horizon without a period, so the plan lives on this note. Design first, then run and review.",
			empty: "Not filled in yet",
			layers: {
				plan: "Plan and design",
				execute: "Execute and review",
			} satisfies Record<FrameworkLayer, string>,
			terms: {
				why: { name: "Why", desc: "Purpose and motivation: why this matters." },
				successState: {
					name: "Success state",
					desc: "Concrete picture of what success looks like.",
				},
				keyResults: {
					name: "Key results",
					desc: "Measurable outcomes that prove success.",
				},
				capabilities: {
					name: "Capabilities",
					desc: "Skills, resources and systems needed.",
				},
				constraints: {
					name: "Constraints",
					desc: "Limits: time, money, energy, rules.",
				},
				risks: {
					name: "Risks",
					desc: "What could derail it, and how you would handle it.",
				},
				outcome: { name: "Outcome", desc: "Desired end result." },
				projects: {
					name: "Projects",
					desc: "One-off initiatives to produce the outcome.",
				},
				habits: { name: "Habits", desc: "Recurring actions that compound." },
				metrics: { name: "Metrics", desc: "Numbers tracked for progress." },
				review: {
					name: "Review",
					desc: "Scheduled reflection or checkpoint.",
				},
				stopList: {
					name: "Stop list",
					desc: "Things to stop doing, to free capacity.",
				},
			} satisfies Record<FrameworkTerm, { name: string; desc: string }>,
		},
		detailsHeading: "Details",
		information: "Task information",
		noteLabel: "Note",
		createdLabel: "Created",
		introCreate: "Give it a title, then choose where it belongs. Only the title is required.",
		introEdit: "Change any part of the task, including its text on the right.",
		issuesTitle: "Fix before saving:",
		notesTitle: "Heads up:",
	},

	/** Explanations shown when a change repairs something. */
	taskNotes: {
		"period-converted": "The period was moved to the matching {level} period.",
		"period-dropped": "Objectives are not time bound, so the period was removed.",
		"period-required": "A period is required on this horizon, so one was filled in.",
		"parent-cleared": "The parent ({parent}) is on a horizon this task cannot link to, so the link was cleared.",
	} satisfies Record<LevelChangeNoteCode, string>,

	/** Reasons a draft cannot be saved. */
	taskIssues: {
		"empty-title": "Give the task a title.",
		"unknown-status": "Pick a status that exists in the registry.",
		"missing-period": "This horizon needs a period.",
		"invalid-period": "The period does not match this horizon's format.",
		"invalid-due": "The due date must be a calendar day, as yyyy-MM-dd.",
		"self-parent": "A task cannot be its own parent.",
		"descendant-parent": "A task cannot link to a task beneath it.",
		"invalid-parent-level": "The parent is on a horizon this task is not meant to link to.",
	} satisfies Record<DraftIssueCode, string>,


	/** Board view copy. `{name}` slots are filled by `formatTemplate`. */
	board: {
		viewTitle: "Task board",
		untitledTask: "Untitled task",
		today: "Today",
		previousPeriod: "Previous period",
		nextPeriod: "Next period",
		searchPlaceholder: "Search tasks",
		allTags: "All tags",
		tagFilterAria: "Filter by tag",
		openNote: "Open task note",
		editTask: "Edit task…",
		deleteTask: "Delete task…",
		changeParent: "Change parent…",
		duplicateTask: "Duplicate",
		copyLink: "Copy link",
		addTask: "Add task",
		addTaskTo: "Add a task to {column}",
		columnAria: "{label}, {count} tasks",
		reorderColumn: "Drag to reorder this column",
		pinnedColumn: "Pinned",
		wipTitle: "Work in progress",
		uncategorized: "Ungrouped",
		cardActions: "Task actions",
		moveToStatus: "Move to {status}",
		moveToTop: "Move to top",
		moveToBottom: "Move to bottom",
		dropHere: "Drop a card here",
		dragInstructions:
			"Press space or enter to pick up a card, the arrow keys to move it, space or enter to drop it, and escape to cancel.",
		duePrefix: "Due",
		childProgress: "{done} of {total} children done",
		allChildrenDone: "All children are done",
		unknownStatus: "Unknown status; shown in the first column",
		emptyTitle: "No tasks on this board yet",
		emptyBody:
			"Tasks are ordinary notes marked with tf-task: true in their frontmatter. The user guide has a full example you can copy.",
		emptyAction: "Open user guide",
		newTask: "New task",
		problemsTitle: "{count} notes need attention",
		problemsBody:
			"These notes are marked as tasks but cannot be placed on a board, because their level is missing or their period is missing or malformed: {paths}",
		problemsMore: "and {count} more",
		copySuffix: "(copy)",
		folderMismatch: "In the wrong folder for its horizon - click to move it to {folder}",
		moveToCorrectFolder: "Move to correct folder",
		unknownStatusHint: "This status is not in the registry; the card is shown in the first column",
	},

	/** The quick-edit popup that opens when a card is clicked. */
	quickEdit: {
		title: "Quick edit",
		level: "Horizon",
		period: "Period",
		parent: "Parent",
		changeParent: "Change…",
		clearParent: "Clear",
		noParent: "No parent",
		tags: "Tags",
		tagsPlaceholder: "Add a tag and press enter",
		tagRemove: "Remove tag {tag}",
		due: "Due",
		children: "Children",
		childrenProgress: "{done}/{total} done",
		bodyTags: "Also tagged in the note: {tags}",
		openNote: "Open note",
		openPane: "Open in new pane",
		delete: "Delete",
		save: "Save",
		cancel: "Cancel",
		close: "Close",
	},

	/** The quick-add popup opened from a column's "+" button. */
	quickAdd: {
		title: "New task",
		titlePlaceholder: "Task title",
		tagsPlaceholder: "Add a tag and press enter",
		tagRemove: "Remove tag {tag}",
		close: "Close",
	},

	/** The folder-scoped parent picker. */
	parentPicker: {
		placeholder: "Search by title or tag",
		allLevels: "All allowed",
		filterLabel: "Filter by horizon",
		empty: "No task on an allowed horizon matches",
		clear: "Clear parent",
		current: "Current parent: {title}",
		nestedUnder: "Under {title}",
	},

	/** Short labels for the horizon switcher tabs. */
	levels: {
		daily: "Daily",
		weekly: "Weekly",
		monthly: "Monthly",
		quarterly: "Quarterly",
		yearly: "Yearly",
		objective: "Objective",
	} satisfies Record<Level, string>,

	/** Longer descriptions, used in the settings tab. */
	levelDescriptions: {
		daily: "One board per calendar day.",
		weekly: "One board per ISO week (Monday to Sunday).",
		monthly: "One board per calendar month.",
		quarterly: "One board per calendar quarter.",
		yearly: "One board per calendar year.",
		objective: "A single permanent board for objectives that are not time bound.",
	} satisfies Record<Level, string>,

	priorities: {
		none: "None",
		low: "Low",
		medium: "Medium",
		high: "High",
		urgent: "Urgent",
	} satisfies Record<Priority, string>,

	sortModes: {
		manual: "Manual (drag to reorder)",
		priority: "Priority",
		due: "Due date",
		created: "Created date",
	} satisfies Record<SortMode, string>,

	rolloverBehaviors: {
		ask: "Ask me first",
		auto: "Roll over automatically",
		never: "Never roll over",
	} satisfies Record<RolloverBehavior, string>,

	statusCategories: {
		todo: "To do",
		active: "Active",
		done: "Done",
		cancelled: "Cancelled",
	} satisfies Record<StatusCategory, string>,

	/** Badge tooltips for broken parent links. */
	hierarchyIssues: {
		"self-link": "This task lists itself as its own parent.",
		"objective-with-parent": "Objectives are roots and cannot have a parent.",
		"invalid-parent-level": "The parent is on a horizon this task cannot link to.",
		"parent-not-found": "The linked parent task could not be found.",
		cycle: "The parent chain loops back on itself.",
	} satisfies Record<HierarchyIssueCode, string>,

	settings: {
		heading: "Horizon Task",
		intro:
			"Tasks live one per markdown note. Each note belongs to exactly one horizon, and each horizon has its own board.",
		pages: {
			general: "General",
			boards: "Boards",
		},
		taskFolder: {
			name: "Task folder",
			desc: "Folder new task notes are created in. Tasks are detected by their frontmatter, not by this folder, so you can move them freely.",
			placeholder: "Tasks/",
			empty: "Enter a folder name, for example Tasks/.",
		},
		folders: {
			heading: "Notes and folders",
			folderPerLevel: {
				name: "One folder per horizon",
				desc: "Store each horizon in its own subfolder of the task folder. The horizon in a note's frontmatter decides which folder it belongs in, and a file in the wrong one is flagged so you can move it with one click.",
			},
			levelFolder: {
				name: "{level} folder",
				desc: "Folder name inside the task folder.",
			},
		},
		colors: {
			heading: "Colours",
			colorBlindSafe: {
				name: "Colour-blind-safe palette",
				desc: "Recolour the statuses that still use a default colour, so status is distinguishable without relying on red and green.",
			},
			contrastWarning: "Low contrast against light or dark themes",
		},
		defaultLevel: {
			name: "Default board on startup",
			desc: "Which horizon to open when the plugin loads.",
		},
		board: {
			heading: "Boards",
			enabledLevels: {
				name: "Enabled horizons",
				desc: "Disabled horizons disappear from the board switcher. Tasks on a disabled horizon are left untouched.",
				atLeastOne: "Keep at least one horizon enabled.",
			},
			sortWithinColumn: {
				name: "Sort within column",
				desc: "Manual order is the order you set by dragging cards.",
			},
			hideEmptyColumns: {
				name: "Hide columns with no tasks",
				desc: "Show only columns that contain at least one card on the current board.",
			},
			collapseEmptyTerminalColumns: {
				name: "Collapse empty done and cancelled columns",
				desc: "Keeps the end of the board tidy when nothing has been finished yet.",
			},
		},
		columns: {
			heading: "Columns",
		},
		hierarchy: {
			heading: "Hierarchy",
			strictHierarchy: {
				name: "Strict hierarchy",
				desc: "Only allow the documented parent horizons, for example daily to weekly or monthly. When off, any different horizon is allowed but invalid links still get a warning badge. A task can have at most one parent, and linking is optional at every level, so parentless tasks are normal.",
			},
		},
		priorities: {
			heading: "Priorities",
			intro:
				"Priorities you want to be able to pick. Hiding one does not change existing tasks.",
			atLeastOne: "Keep at least one priority enabled.",
		},
		cards: {
			heading: "Cards",
			priority: "Show priority",
			tags: "Show tags",
			due: "Show due date",
			parent: "Show parent link",
			childProgress: "Show child progress",
			period: "Show horizon and period",
		},
		rollover: {
			heading: "Rollover",
			intro:
				"What to do with tasks that were not finished when a period ended. Objectives are not time bound and never roll over.",
		},
		kanban: {
			heading: "Kanban",
			intro: "How this board arranges its columns and rows.",
			groupBy: {
				name: "Group columns by",
				desc: "Which property becomes the columns. Changing it changes the column set.",
			},
			swimLane: {
				name: "Swimlanes",
				desc: "Optional second grouping across the board. Each cell is an independent drop target.",
			},
			columnWidth: { name: "Column width", desc: "Between 200 and 500 pixels." },
			maxSwimLaneHeight: {
				name: "Max swimlane height",
				desc: "Between 300 and 1200 pixels before a swimlane row scrolls.",
			},
			hideEmptySwimLanes: {
				name: "Hide empty swimlanes",
				desc: "Hide swimlane rows that have no visible cards.",
			},
			cardLayout: { name: "Card layout", desc: "Standard or compact card density." },
			explodeListColumns: {
				name: "Show items in multiple columns",
				desc: "A task with several tags appears in each of its tag columns.",
			},
			pinnedColumns: {
				name: "Pinned columns",
				desc: "Comma-separated column values kept visible even when empty.",
			},
			wipLimits: {
				name: "WIP limits",
				desc: 'JSON mapping a column value to a limit, for example {"in-progress":5}.',
			},
		},
		kanbanOptions: {
			groupBy: { status: "Status", priority: "Priority", tags: "Tags" },
			swimLane: { none: "None", priority: "Priority", tags: "Tags" },
			cardLayout: { default: "Standard", compact: "Compact" },
		},
		statuses: {
			heading: "Statuses",
			listName: "Columns",
			desc: "Columns of this board, in order. Renaming or recolouring never touches your task notes; deleting a status moves this board's tasks to the one you pick.",
			boardDesc: "Columns for this board.",
			add: "Add status",
			archiveAfter: "Archive after (minutes)",
			newLabel: "New status",
			label: "Label",
			color: "Colour",
			category: "Category",
			moveUp: "Move up",
			moveDown: "Move down",
			delete: "Delete",
			lastStatus: "Keep at least one status.",
			deleteTitle: "Delete status “{label}”?",
			deleteBody:
				"Every task using this status is moved to the status you pick. Task notes are rewritten, so this cannot be undone from the board.",
			deleteReplacement: "Move tasks to",
			deleteConfirm: "Delete status",
			deleteCancel: "Cancel",
		},
		help: {
			guide: {
				name: "User guide",
				desc: "Open the full guide: concepts, the frontmatter reference, the hierarchy rules, keyboard shortcuts and troubleshooting.",
			},
		},
	},

	notices: {
		settingsSaveFailed:
			"Horizon Task could not save your settings. See the developer console for details.",
		writeFailed:
			"Horizon Task could not save a task, so the change was undone. See the developer console for details.",
		createFailed:
			"Horizon Task could not create the task note. See the developer console for details.",
		deleteFailed:
			"Horizon Task could not move the task note to the trash. See the developer console for details.",
		taskMoved:
			"Task moved. Use the {command} command if that was not what you wanted.",
		undo: "Undo",
		nothingToUndo: "There is no task change to undo.",
		undoDone: "Undone.",
		deleteTitle: "Delete this task?",
		deleteBody:
			"The note will be moved to the trash, where you can restore it. Tasks that link to it will show a missing parent warning.",
		deleteConfirm: "Move to trash",
		moveFailed:
			"Horizon Task could not move the note. See the developer console for details.",
		folderMoved: "Moved to {folder}",
		duplicated: "Created {title}",
		linkCopied: "Link copied to the clipboard.",
		copyFailed: "Could not reach the clipboard. The link is {link}",
		parentChanged: "Parent updated.",
		contrastWarning: "{color} has low contrast against light or dark themes.",
	},

	guide: {
		title: "Horizon Task user guide",
	},
} as const;

/**
 * The in-app user guide, authored as markdown.
 *
 * It is rendered by Obsidian's own markdown renderer, so it picks up the user's
 * theme, fonts and code-block styling instead of inventing its own. It lives
 * here with the rest of the copy rather than under `ui/` because it is
 * user-facing text: translating the plugin means replacing this array and the
 * `strings` object above, and nothing else.
 *
 * Stored as one string per line rather than a single literal so the markdown -
 * including its code fences - stays readable and diffable.
 *
 * `{{version}}` is substituted at render time by `buildGuideMarkdown`.
 */
export const GUIDE_BODY: readonly string[] = [
	"# Horizon Task user guide",
	"",
	"Version {{version}}.",
	"",
	"You can reopen this guide at any time: run **Open user guide** from the command palette, or use the Help section at the bottom of the plugin's settings.",
	"",
	"## What this plugin does",
	"",
	"Horizon Task turns a vault into a hierarchical, multi-horizon task manager.",
	"",
	"- Every task is its own markdown note, so it links, tags, searches and syncs like any other note you have.",
	"- Every task belongs to exactly **one horizon**: `daily`, `weekly`, `monthly`, `quarterly`, `yearly` or `objective`.",
	"- Every horizon has a Kanban board scoped to a period - one day, one ISO week, one month, one quarter or one year. Objectives are not time bound and share a single permanent board.",
	"- A task can link up to **one parent** on a coarser horizon, forming a goal tree. A parent card shows progress from its children instead of pulling those children onto its own board.",
	"",
	"## What is available right now",
	"",
	"| Capability | Status |",
	"| --- | --- |",
	"| One note per task, the frontmatter model, period maths, hierarchy validation | Available now |",
	"| Settings, the command palette entry and this guide | Available now |",
	"| Board view: horizon tabs, period navigation, status columns, cards, tags, priority, progress rollups | Available now |",
	"| Drag and drop by mouse, keyboard and touch | Available now |",
	"| Task form, quick add, inline rename, parent picker, move to status | Available now |",
	"| Quick edit popup, folder-per-level storage, status-coloured cards | Available now |",
	"| Rollover of unfinished tasks, unlinked filter, suggest parents | Planned |",
	"",
	"Everything described below already works. The board reads any note you write by hand that carries the task marker, so the frontmatter reference further down is all you need to get going.",
	"",
	"## Getting around the board",
	"",
	"Open the board in either of two ways:",
	"",
	"- the stacked-layers ribbon icon in the left sidebar, or",
	"- the command palette: **Horizon Task: Open board**.",
	"",
	"It opens as an ordinary tab, so you can keep it next to the notes you are working on. Only one board tab is ever created - asking for the board again brings the existing tab forward.",
	"",
	"| Control | What it does |",
	"| --- | --- |",
	"| Horizon tabs | Switch between daily, weekly, monthly, quarterly, yearly and objectives. Horizons you disable in settings are hidden. |",
	"| `‹` and `›` | Step to the previous or next period. |",
	"| Today | Jump back to the period you are in right now. |",
	"| Tag filter | Show only cards carrying one tag. Clicking a tag chip on a card applies it here too. |",
	"| Search | Matches card titles, tags and file paths. |",
	"| A card | Opens the quick edit popup for that task, without leaving the board. |",
	"",
	"The board remembers the horizon and period you were last looking at, so restarting the app puts you back where you were.",
	"",
	"## Moving cards",
	"",
	"Drag a card into another column to change its status, or up and down inside a column to set its order. Both are written straight back to the note, and the order survives a restart.",
	"",
	"| With | What to do |",
	"| --- | --- |",
	"| Mouse | Drag a card. A plain click opens the quick edit popup instead, because a drag only begins once the pointer has moved a little. |",
	"| Touch | Press and hold a card for a moment, then drag. A quick tap opens the quick edit popup and a swipe scrolls the column, so neither gets in the way. |",
	"| Keyboard | Focus a card with tab, press space or enter to pick it up, use the arrow keys to move it, press space or enter to drop, and escape to cancel. |",
	"",
	"Moving a card into a status in the done category stamps its `completed` date; moving it back out clears that date again.",
	"",
	"### Moving a card without dragging",
	"",
	"Dragging is never the only way. Right-click a card - or use its actions button on a phone or tablet - for **Move to ...** for every status, plus **Move to top** and **Move to bottom**. That menu does exactly what a drag does, so it is a real alternative and not a degraded one.",
	"",
	"The same menu holds the rest of a card's actions: **Open note**, **Edit task...** for the full form, **Change parent...**, **Duplicate**, **Copy link** and **Delete task...**. **Copy link** puts a `[[wikilink]]` to the note on your clipboard, which is the quickest way to reference a task from somewhere else.",
	"",
	"## Creating and editing tasks",
	"",
	"| To | Do this |",
	"| --- | --- |",
	"| Add a task to this board | **New task** in the board header, or **New task** from the command palette. |",
	"| Add several in a row | Click **+** in a column header and type. Press enter to save each one; the box stays open for the next. |",
	"| Rename a card | Double-click its title, type, then press enter. Escape abandons the change. |",
	"| Edit a task properly | Right-click the card, or use its actions button on a phone, then **Edit task...**. |",
	"| Delete a task | The same menu, **Delete task...**. The note goes to the trash, after a confirmation. |",
	"",
	"The form covers the title, status, priority, horizon, period, parent, tags, due date and, for a new task, the opening body text. It writes only the fields you actually changed, so nothing else in the note is touched - including frontmatter from other plugins.",
	"",
	"### The quick edit popup",
	"",
	"Clicking a card opens a small popup anchored to it, so you can fix a status or add a due date without opening anything or losing your place. It edits the title, status, priority, parent, tags and due date.",
	"",
	"Double-clicking a card, or Ctrl/Cmd-clicking it, opens the task's note instead. Double-clicking the title alone renames it in place. The parent chip on a card opens the parent's note, and the tags are suggestions from tags already used in the vault.",
	"",
	"| Part | What it does |",
	"| --- | --- |",
	"| Title | Focused when the popup opens. Saves on enter or when you click away. |",
	"| Horizon and period | Shown but not editable: changing a horizon moves the note and rescopes the parent link, which belongs in the full form. |",
	"| Parent | Shows the current parent, with **x** to clear it and **Change** to pick another. |",
	"| Tags | Editable chips. Tags written in the note's own text are listed separately and never duplicated into frontmatter. |",
	"| Children | How many child tasks are done, with their progress bar. |",
	"",
	"Every change is written as you make it, which is why the card behind the popup updates immediately. **Save** writes and closes, **Cancel** puts every field back the way it was, escape closes and cancels, and ctrl/cmd and enter saves. The footer also has **Open note**, **Open in new pane** and **Delete**. Double-clicking a card's title still renames it in place, without opening the popup.",
	"",
	"### Choosing a parent",
	"",
	"**Choose** opens a search box listing only the tasks that may legally be that parent - the right horizon, never the task itself, and never anything beneath it. Chips above the box narrow the list to one horizon, the first row clears the link when a parent is already set, and every row shows the task's horizon, period, status and own parent, because the same title often exists on several boards at once. Searching matches titles, note names and tags. A parent is always optional.",
	"",
	"### Changing the horizon",
	"",
	"Moving a task to another horizon repairs what it would break, and says what it did:",
	"",
	"- the period is re-expressed on the new horizon, so a task on 28 September 2026 becomes the week that contains it (`2026-W40`) instead of losing its period;",
	"- a parent on a horizon the task may no longer link to is cleared, and the form names it so you can choose another.",
	"",
	"Objectives are not time bound, so moving a task to or from `objective` adds or removes the period accordingly.",
	"",
	"### Taking a change back",
	"",
	"Edits are recorded, and **Undo last task change** from the command palette writes the previous values back. Moving a task to another board also offers an Undo button in the notification, because that is the change most likely to surprise.",
	"",
	"## Core concepts",
	"",
	"### Horizons and periods",
	"",
	"Each horizon stores its period in a fixed format. This is what goes in the `period` field:",
	"",
	"| Horizon | Period format | Example | The board covers |",
	"| --- | --- | --- | --- |",
	"| daily | `yyyy-MM-dd` | `2026-09-28` | one calendar day |",
	"| weekly | `yyyy-'W'ww` | `2026-W40` | Monday to Sunday, ISO 8601 |",
	"| monthly | `yyyy-MM` | `2026-09` | one calendar month |",
	"| quarterly | `yyyy-'Q'q` | `2026-Q4` | one calendar quarter |",
	"| yearly | `yyyy` | `2026` | one calendar year |",
	"| objective | no period | - | one permanent board |",
	"",
	"Weekly boards use ISO 8601 weeks, so a week starts on Monday and belongs to a week-numbering year that is not always the calendar year. Two examples worth knowing: 1 January 2021 falls into `2020-W53`, and 2026 is a 53-week year, so 1 January 2027 still belongs to `2026-W53`. The plugin handles these boundaries, including week 53 and leap years.",
	"",
	"### One board per task",
	"",
	"A task appears on exactly one board - the board for its own horizon. A daily task never shows up on the weekly board, and a weekly task never shows up on the daily board. Cross-horizon context comes from parent links and the progress rollup on the parent card, not from duplicating cards.",
	"",
	"### Where your task notes live",
	"",
	"With **One folder per horizon** switched on (the default), each horizon keeps its notes in its own folder inside the task folder:",
	"",
	"```text",
	"Tasks/",
	"  Daily/        2026-09-28 Ship v1 landing page.md",
	"  Weekly/       2026-W40 Launch website.md",
	"  Monthly/      2026-09  Harden the API.md",
	"  Quarterly/",
	"  Yearly/",
	"  Objectives/",
	"```",
	"",
	"The `level` in a note's frontmatter decides which folder it belongs in - never the other way round. That ordering is what makes moving a task safe: change the horizon and the note is moved for you, with **FileManager.renameFile**, so every wikilink pointing at it is rewritten and nothing is left broken.",
	"",
	"If a note ends up in the wrong folder - because it was dragged there by hand, or because the folder names changed - the card grows a warning badge. Click it to move the note where it belongs. Nothing is ever moved silently.",
	"",
	"Folder names are yours to choose in settings, and switching the setting off gives you the flat layout instead: every task directly in the task root, and no folder warnings at all.",
	"",
	"### The goal tree",
	"",
	"A task may have zero or one parent, and that parent always sits on a coarser horizon:",
	"",
	"| If the task is | its parent may be |",
	"| --- | --- |",
	"| `daily` | weekly or monthly |",
	"| `weekly` | monthly or quarterly |",
	"| `monthly` | quarterly or yearly |",
	"| `quarterly` | yearly or objective |",
	"| `yearly` | objective |",
	"| `objective` | nothing - objectives are roots |",
	"",
	"**Linking is optional at every level.** A task with no parent is completely valid on every board and never shows a warning. Linking is encouraged, never required, and a task never has more than one parent.",
	"",
	"Because a parent is always on a coarser horizon, the goal tree cannot contain a loop. The plugin still checks for damage from hand-edited notes: a task that lists itself as its own parent, or a chain that loops back on itself, gets a warning badge on its card. Nothing is rewritten behind your back - right-click the card, choose **Edit task...**, and pick a valid parent or clear the link.",
	"",
	"### Statuses",
	"",
	"Every board has its own statuses, which are its columns in order. Each board starts with the same defaults, and you can add, rename, recolour, reorder or delete them per board in **Settings → Horizon Task → [board]**. Out of the box:",
	"",
	"- `backlog` and `todo` - the todo category",
	"- `in-progress` and `blocked` - the active category",
	"- `done` - the done category",
	"- `cancelled` - the cancelled category",
	"",
	"The category drives behaviour: moving a task into a `done` status stamps the `completed` date, and moving it back out clears that date. A parent is never marked done automatically when all its children finish - the card shows a hint and offers a one-click action instead.",
	"",
	"### How a card reads",
	"",
	"Every card carries a 4px bar down its leading edge in its status's colour, so a column can be scanned by colour alone. Priority stays a chip on the card, deliberately *not* a second coloured bar, so the two signals never compete for the same edge.",
	"",
	"Three states are readable without reading:",
	"",
	"- a **done** card is dimmed and its title recedes;",
	"- a **cancelled** card has a struck-through title;",
	"- **urgent** priority adds a small dot, which leaves the status bar meaning exactly one thing.",
	"",
	"Because colour carries meaning here, the colours are checked rather than assumed. Every default meets WCAG AA contrast (3:1) against both a light and a dark background, and **Colour-blind-safe palette** in settings recolours every status that is still on a default colour - statuses you recoloured yourself are left alone. A status colour that fails the contrast check is called out in the settings tab and in the status list.",
	"",
	"A task stores the status **id**, so renaming a label never touches your task notes. Deleting a status is a migration: you choose the replacement and every task using it is moved.",
	"",
	"### Ordering inside a column",
	"",
	"Manual order is stored in the `order` field as a short base-62 key rather than a number - a technique called fractional indexing. Dropping a card between two others rewrites only that one card, which keeps reordering cheap when every task is a separate file, and unlike decimal numbers the keys never run out of precision no matter how often you insert into the same gap.",
	"",
	"## Creating your first task",
	"",
	"1. Add `tf-task: true` to the frontmatter. That marker is what makes a note a task.",
	"2. Give it a `level` and, unless the level is `objective`, a `period` in the matching format.",
	"",
	"The usual way is the **New task** button in the board header, or **New task** from the command palette: the form opens with the horizon and period of the board you are looking at, so the task lands where you expect. Writing notes by hand works just as well, since everything the form does is frontmatter.",
	"",
	"Here is a complete daily task:",
	"",
	"```yaml",
	"---",
	"tf-task: true",
	"title: Ship v1 landing page",
	"status: in-progress",
	"priority: high",
	"level: daily",
	"period: 2026-09-28",
	"parent: \"[[2026-W40 Launch website]]\"",
	"order: a0",
	"tags: [work, website]",
	"due: 2026-09-30",
	"created: 2026-09-28",
	"completed: null",
	"---",
	"",
	"Body text, checklists and inline #hashtags all live here.",
	"```",
	"",
	"### Frontmatter reference",
	"",
	"| Field | Required | Meaning |",
	"| --- | --- | --- |",
	"| `tf-task` | yes | Marks the note as a task. Notes without it are ignored completely. |",
	"| `title` | no | Display title. Falls back to the file name. |",
	"| `status` | yes | A status id such as `todo`, `in-progress` or `done`. |",
	"| `priority` | no | `none`, `low`, `medium`, `high` or `urgent`. Defaults to `none`. |",
	"| `level` | yes | `daily`, `weekly`, `monthly`, `quarterly`, `yearly` or `objective`. |",
	"| `period` | for every horizon except objective | The period the task belongs to, in its horizon's format. |",
	"| `parent` | no | A wikilink to the single parent task. |",
	"| `order` | no | Fractional index controlling manual order within its column. |",
	"| `tags` | no | Tags. Inline #hashtags in the body are read as well, and are never copied into this field. |",
	"| `due` | no | Due date as `yyyy-MM-dd`. |",
	"| `created` | no | Creation date as `yyyy-MM-dd`. |",
	"| `completed` | no | Set automatically when the status moves into a done status. |",
	"| `carriedFrom` | no | The period a task was rolled over from. |",
	"",
	"Any frontmatter field the plugin does not recognise is preserved untouched whenever it writes to a note.",
	"",
	"## Rollover",
	"",
	"Incomplete tasks can be carried into the next period. Rollover is opt-in per horizon, with three behaviours: **ask me first**, **roll over automatically**, or **never**. The default is to ask, because silently moving your tasks when the app starts would be surprising.",
	"",
	"When a period has just started and the one before it left work behind, the board shows a non-blocking banner: how many tasks were carried over, with **Review**, **Roll over all** and **Dismiss**. A rolled-over task keeps its parent link and records where it came from in `carriedFrom`.",
	"",
	"Objectives are not time bound, so they never roll over.",
	"",
	"## Settings reference",
	"",
	"| Setting | Default | What it does |",
	"| --- | --- | --- |",
	"| Task folder | `Tasks/` | Where new task notes are created. Tasks are detected by frontmatter, not by this folder. |",
	"| One folder per horizon | on | Store each horizon in its own subfolder of the task folder, and flag notes that sit in the wrong one. |",
	"| Horizon folder names | Daily, Weekly, ... | The folder name used for each horizon. |",
	"| Colour-blind-safe palette | off | Recolour every status that is still on a default colour. |",
	"| Default board on startup | Daily | Which horizon the board opens on. |",
	"| Enabled horizons | all six | Disabled horizons disappear from the board switcher; their tasks are left untouched. |",
	"| Sort within column | Manual | Manual drag order, or sorted by priority, due date or created date. |",
	"| Hide columns with no tasks | off | Show only columns that hold a card on the current board. |",
	"| Collapse empty done and cancelled columns | on | Keeps the end of the board tidy. |",
	"| Strict hierarchy | on | Enforce the parent table above. Turn it off to allow any other horizon, with a warning badge still shown on invalid links. |",
	"| Priorities | all | Which priorities are offered when editing a task. |",
	"| Show tags, due date, parent, child progress | on | What each card displays. |",
	"| Rollover, per horizon | Ask | Ask, automatic or never, chosen independently for each horizon. |",
	"",
	"## Keyboard shortcuts",
	"",
	"| Shortcut | Action |",
	"| --- | --- |",
	"| Ctrl/Cmd + Alt + left or right arrow | Previous or next period |",
	"| Ctrl/Cmd + Alt + T | Jump to the current period |",
	"| Space | Lift a focused card, arrow keys to move it, Space to drop, Escape to cancel |",
	"",
	"The horizon shortcuts ship with the plugin. The card keys work whenever a card has focus, as part of keyboard drag and drop.",
	"",
	"## Troubleshooting",
	"",
	"### A card shows a hierarchy warning",
	"",
	"The parent link breaks the parent table, points at a note that is not a task, or loops back on itself. Nothing has been changed in your note: right-click the card, choose **Edit task...**, and pick a valid parent or clear the link.",
	"",
	"### A task does not appear on the board",
	"",
	"Check three things: the note has `tf-task: true`, its `level` is one of the six horizons, and its `period` is in the format for that horizon.",
	"",
	"### The board says a note needs attention",
	"",
	"A banner above the columns lists notes that are marked as tasks but cannot be placed anywhere, because their `level` is missing or their `period` is missing or malformed. Fix the frontmatter and the card appears on the right board - nothing is hidden from you silently.",
	"",
	"### I moved or renamed a task note",
	"",
	"That is safe. A task's identity is its file path, and Obsidian updates wikilinks when you move a note, so parent links follow along automatically.",
	"",
	"### Why is a task only on one board?",
	"",
	"That is by design - see **One board per task** above. Use a parent link and the rollup instead of duplicating the card.",
	"",
	"### Mobile",
	"",
	"Everything works on mobile. Dragging needs a short press-and-hold so that scrolling still works, and every card also carries an actions button that opens the same menu as a right-click on the desktop, with **Move to ...** for each status.",
	"",
	"## Privacy",
	"",
	"Horizon Task makes no network requests and collects no telemetry. Your tasks never leave your vault.",
];

